# ECON622: Assignment 4

# Q1

Install Conda, [VS Code Python
Extension](https://marketplace.visualstudio.com/items?itemName=ms-python.python),
[Black
Formatter](https://marketplace.visualstudio.com/items?itemName=ms-python.black-formatter),
[GitHub
Copilot](https://marketplace.visualstudio.com/items?itemName=GitHub.copilot)
and [GitHub Copilot
Chat](https://marketplace.visualstudio.com/items?itemName=GitHub.copilot-chat)

You will need to be on python 3.11 for certain packages to work. The
recommendation is always to use a conda environment Set up a conda
environment to work in for this course and to practice virtual
environments, and then install the packages -
`conda create -n econ622 python=3.11` - `conda activate econ622` -
`pip install -r requirements.txt`

Some imported packages which will tell you if you have a successful
installation

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy
import pandas as pd
import torch
import jax
import jax.numpy as jnp
import jax.numpy as jnp
from jax import grad, hessian

Mess around with your setup until the following work

In [2]:
x = torch.zeros((2, 3))
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [3]:
x = jnp.zeros((2, 3))
print(x)

[[0. 0. 0.]
 [0. 0. 0.]]

No need to get GPUs/etc. working. If you have issues on windows, see
[JAX
Installation](https://jax.readthedocs.io/en/latest/installation.html#cpu)
and [Pytorch Installation](https://pytorch.org/get-started/locally/)
instructions

## Q2

This section just summarizes some reading on how JAX works, and asks you
to come up with some demonstrations of its functionality. Read: - [JAX
Quickstart](https://jax.readthedocs.io/en/latest/notebooks/quickstart.html) -
[JAX
Basics](https://jax.readthedocs.io/en/latest/jax-101/01-jax-basics.html) -
[JAX
Jit](https://jax.readthedocs.io/en/latest/jax-101/02-jitting.html) -
[JAX
Vectorization](https://jax.readthedocs.io/en/latest/jax-101/03-vectorization.html) -
[JAX
AD](https://jax.readthedocs.io/en/latest/jax-101/04-advanced-autodiff.html)

## Q2.1

Write a function which takes a normally distributed random number and
calculates the standard deviation manually (i.e. calculate the mean,
second moment, etc. manually and then form the standard deviation
yourself in the function)

Compile the function using the `jit` and the decorator `@jit`

In [4]:
# MODIFY HERE

## Q2.2

Now take that function and generate a matrix of random normals and use
`vmap` to calculate the standard deviation across rows, then across
columns. Compare to `jnp.std(x, axis=0)` and `jnp.std(x, axis=1)`

In [5]:
# MODIFY HERE

## Q2.3

Take the following code, and find the hessian of `f` at `x`

In [6]:
# Define a multivariate function
def f(x):
    return jnp.sum(x ** 2)

# Define a point at which to evaluate the function
x = jnp.array([1.0, 2.0, 3.0])

# Q3

In this section you will explore solving linear systems with scipy and
JAX.

It will use the continuous time markov chain example in the [iterative
notes](https://ubcecon.github.io/ECON622/lectures/lectures/iterative_methods.html#/example-from-previous-lectures)
with an intensity $a > 0$ you gain a count, and $b > 0$ you lose a
count.

## Q3.1

The example for a continuous time Markov Chain with a counting process
in [Factorization
Notes](https://ubcecon.github.io/ECON622/lectures/lectures/factorizations_direct_methods.html#/finding-the-stationary-distribution)
was written in Julia.

Figure out how to do this with Python scipy using direct methods. You
can explore scipy in doing so. See [ECON526
Notes](https://ubcecon.github.io/ECON526/lectures/lectures/linear_algebra_foundations.html#/title-slide)
for some help if you are having trouble navigating scipy.

Your code should: 1. Find the stationary distribution 2. Solve the
bellman equation with those parameters in the linked notes.

In [7]:
# MODIFY HERE

Don’t worry about the tridiagonal structure, which is harder to work
with in python packages.

## Q3.2

Now do the same thing but instead of using Python scipy, make sure to
use the JAX versions of those packages (e.g. `jax.scipy.linalg.solve`
and `jax.scipy.linalg.eig`)

In [8]:
# MODIFY HERE

## Q3.3

Solve the bellman equation from our example using
[lineax](https://docs.kidger.site/lineax/api/linear_solve/) and JAX. For
this we want to use iterative methods along the lines of our [Iterative
Notes](https://ubcecon.github.io/ECON622/lectures/lectures/iterative_methods.html#/title-slide)

In [9]:
import lineax

## Q3.4

Your JAX code for the bellman equation should be providing a solution
for all states. Create a function to find what the value is in the first
state (i.e, starting at count of 1),

-   To do this, you will want to wrap code that creates the intensity
    matrix given the parameters
-   Then wrap the solve using that intensity matrix and the discounting
-   Then finally returns the `v[0]` from the resulting value function

In [10]:
# MODIFY HERE

Then, use JAX and `grad` to differentiate the value function with
respect to the $a$ parameter (and $b, \rho$ and $r$ if you wish)

In [11]:
# MODIFY HERE

## Q3.5 (BONUS)

Now try to do the same thing with mean of the stationary distribution 1.
write a function which takes in the `a, b` and `r` parameters and
creates the markov chain 2. Within that function, you will probably want
to focus on functions which only give you a particular
eigenvalue/eigenvector - as selecting a particular eigenvector isn’t
differentiable 3. Then normalize the eigenvector to get the stationary
distribution and return its expectation using `r`

In [12]:
# MODIFY HERE

Finally, using that function, calculate the gradient of the expectation
with respect to the `a` parameter

In [13]:
# MODIFY HERE

## Q3.6 (BONUS)

Try to figure out how to solve for the stationary distribution and
bellman equation using lazy matrix-free methods in python. It isn’t
obvious the packages to use for this but my guess is that your best bet
is to use the new package [CoLA](https://github.com/wilson-labs/cola)

Get it working with iterative methods and the matrix-free operators and
submit bug reports on that repo if it is not.

In [14]:
# import cola
# MODIFY HERE